# Generated by Django 2.2.2 on 2019-06-19 08:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('audio_link', models.CharField(max_length=500)),
                ('definitions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('part_of_speech', models.CharField(max_length=250)),
                ('examples', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=250)),
                ('meaning', models.TextField(default='')),
                ('local_word', models.CharField(max_length=1000)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='crawler.Word')),
            ],
        ),
    ]
