# Generated by Django 2.2.2 on 2019-06-19 11:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='word',
            name='definitions',
        ),
        migrations.RemoveField(
            model_name='word',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='word',
            name='part_of_speech',
        ),
        migrations.RemoveField(
            model_name='word',
            name='synonyms',
        ),
        migrations.AddField(
            model_name='translation',
            name='utf_encoded',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='word',
            name='audio_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
        ),
        migrations.AddField(
            model_name='word',
            name='pronounciations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='translation',
            name='local_word',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(max_length=250)),
                ('examples', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None)),
                ('priority', models.IntegerField(default=0)),
                ('definitions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenitions', to='crawler.Word')),
            ],
        ),
    ]
