# Generated by Django 2.2.2 on 2019-06-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20190619_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='word',
            new_name='english_word',
        ),
        migrations.RenameField(
            model_name='worddefinition',
            old_name='word',
            new_name='english_word',
        ),
    ]
